/* Generated By:JavaCC: Do not edit this line. ExprConstants.java */
public interface ExprConstants {

  int EOF = 0;
  int chiffre = 8;
  int entier = 9;
  int lettre = 10;
  int ident = 11;
  int chaine = 12;
  int PARENTOUV = 13;
  int PARENTFERM = 14;
  int PLUS = 15;
  int MOINS = 16;
  int MULT = 17;
  int DIV = 18;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 6>",
    "\"*)\"",
    "<chiffre>",
    "<entier>",
    "<lettre>",
    "<ident>",
    "<chaine>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
  };

}
