/* Generated By:JavaCC: Do not edit this line. GramConstants.java */
public interface GramConstants {

  int EOF = 0;
  int DOC = 5;
  int FINDOC = 6;
  int TITRE = 7;
  int FINTITRE = 8;
  int DATE = 9;
  int FINDATE = 10;
  int PARA = 11;
  int FINPARA = 12;
  int ENTIER = 13;
  int CHIFFRE = 14;
  int IDENT = 15;
  int LETTRE = 16;
  int ETOILE = 17;
  int VIRGULE = 18;
  int POINT = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"doc\"",
    "\"findoc\"",
    "\"titre\"",
    "\"fintitre\"",
    "\"date\"",
    "\"findate\"",
    "\"para\"",
    "\"finpara\"",
    "<ENTIER>",
    "<CHIFFRE>",
    "<IDENT>",
    "<LETTRE>",
    "\"*\"",
    "\",\"",
    "\".\"",
  };

}
