/* Generated By:JavaCC: Do not edit this line. YakaConstants.java */
public interface YakaConstants {

  int EOF = 0;
  int chiffre = 8;
  int entier = 9;
  int lettre = 10;
  int ident = 11;
  int chaine = 12;
  int CONST = 13;
  int VAR = 14;
  int PROGRAMME = 15;
  int FPROGRAMME = 16;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 6>",
    "\"*)\"",
    "<chiffre>",
    "<entier>",
    "<lettre>",
    "<ident>",
    "<chaine>",
    "\"CONST\"",
    "\"VAR\"",
    "\"PROGRAMME\"",
    "\"FPROGRAMME\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"VRAI\"",
    "\"FAUX\"",
    "\"ENTIER\"",
    "\"BOOLEEN\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"+\"",
    "\"-\"",
    "\"OU\"",
    "\"*\"",
    "\"/\"",
    "\"ET\"",
    "\"NON\"",
  };

}
